// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZQLky87GWco62fT7jCz5g_GJBiZahTk',
    appId: '1:386198984140:web:2c45f6368f5358c641f969',
    messagingSenderId: '386198984140',
    projectId: 'mirror-laikipia',
    authDomain: 'mirror-laikipia.firebaseapp.com',
    storageBucket: 'mirror-laikipia.firebasestorage.app',
    measurementId: 'G-JRTGSM4MLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD44DX6hgaOnztSacVP-bhJC523zTpOc-I',
    appId: '1:386198984140:android:d16ebe33c2cc43ba41f969',
    messagingSenderId: '386198984140',
    projectId: 'mirror-laikipia',
    storageBucket: 'mirror-laikipia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe3tWainl-RxQokZy1CgHSfilZ9SaWR24',
    appId: '1:386198984140:ios:7cc96a8d919bc59241f969',
    messagingSenderId: '386198984140',
    projectId: 'mirror-laikipia',
    storageBucket: 'mirror-laikipia.firebasestorage.app',
    iosBundleId: 'com.example.mirrorLaikipia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe3tWainl-RxQokZy1CgHSfilZ9SaWR24',
    appId: '1:386198984140:ios:7cc96a8d919bc59241f969',
    messagingSenderId: '386198984140',
    projectId: 'mirror-laikipia',
    storageBucket: 'mirror-laikipia.firebasestorage.app',
    iosBundleId: 'com.example.mirrorLaikipia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPZQLky87GWco62fT7jCz5g_GJBiZahTk',
    appId: '1:386198984140:web:5161843222ddd43141f969',
    messagingSenderId: '386198984140',
    projectId: 'mirror-laikipia',
    authDomain: 'mirror-laikipia.firebaseapp.com',
    storageBucket: 'mirror-laikipia.firebasestorage.app',
    measurementId: 'G-LRT3YTM5HG',
  );
}
